version: "3.9"

services:
  django:
    build:
      context: ./server
      dockerfile: ./compose/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/server
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
    networks:
      - bastionnet
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - bastionnet
  node:
    build:
      context: ./client
      dockerfile: ./compose/Dockerfile
    command: npm start
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - 3000:3000
      - 3001:3001
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - bastionnet
  
volumes:
  postgres_data:

networks:
  bastionnet:
    driver: bridge
