# Generated by Django 3.2.11 on 2022-01-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_user', models.CharField(editable=False, max_length=255)),
                ('activity_date', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('pigment', models.TextField(help_text='The color', max_length=255)),
                ('hexcode', models.TextField(help_text='The hexcode', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'colors',
            },
        ),
    ]
